const constantDataType = {
    INITIAL_APP_LOAD: 'INITIAL_APP_LOAD',
    ALL_DATA_LOADED_FROM_API: 'ALL_DATA_LOADED_FROM_API',
    SEARCH_CITY: 'SEARCH_CITY',
    SEARCH_CITY_FOCUS: 'SEARCH_CITY_FOCUS',
    SEARCH_VALUE_UPDATE: 'SEARCH_VALUE_UPDATE',
    SEARCH_LOCATION_WISE: 'SEARCH_LOCATION_WISE'
}

export default constantDataType